# Generated by Django 5.2.4 on 2025-08-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('flood', 'Flood'), ('fire', 'Fire'), ('earthquake', 'Earthquake'), ('storm', 'Storm'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
