# Generated by Django 5.2.4 on 2025-08-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relief_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('report_type', models.CharField(choices=[('emergency', 'Emergency'), ('request', 'Request'), ('feedback', 'Feedback')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('skills', models.TextField(help_text='List of skills (e.g., First Aid, Driving, Cooking)')),
                ('availability', models.CharField(help_text='e.g., Weekends, Evenings', max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
